{{- range $key, $workload := .Values.workloads }}
{{- $config := default (dict) $workload.config }}
{{- if and (ne $workload.enabled false) (eq $config.enabled true) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application-stack.workloadFullname" (list $ $key $workload) }}-config
  labels:
    {{- include "application-stack.workloadLabels" (list $ $key $workload) | nindent 4 }}
data:
  {{- toYaml (default (dict) $config.data) | nindent 2 }}
{{- end }}
{{- end }}
