{{- range $key, $workload := .Values.workloads }}
{{- $secret := default (dict) $workload.secret }}
{{- if and (ne $workload.enabled false) (eq $secret.enabled true) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application-stack.workloadFullname" (list $ $key $workload) }}-secret
  labels:
    {{- include "application-stack.workloadLabels" (list $ $key $workload) | nindent 4 }}
type: {{ default "Opaque" $secret.type }}
{{- with $secret.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with $secret.stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
