{{- if ne .Values.serviceAccount.create false -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "application-stack.serviceAccountName" . }}
  labels:
    {{- include "application-stack.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
