{{- range $key, $workload := .Values.workloads }}
{{- $service := default (dict) $workload.service }}
{{- if and (ne $workload.enabled false) (ne $service.enabled false) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-stack.workloadFullname" (list $ $key $workload) }}
  labels:
    {{- include "application-stack.workloadLabels" (list $ $key $workload) | nindent 4 }}
  {{- with $service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ default "ClusterIP" $service.type }}
  ports:
    - port: {{ default 80 $service.port }}
      targetPort: {{ default "http" $service.targetPort }}
      protocol: TCP
      name: http
      {{- with $service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "application-stack.selectorLabels" (list $ $key $workload) | nindent 4 }}
{{- end }}
{{- end }}
