apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-stack-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: application-stack
  source:
    repoURL: git@github.com:Nasruddinkhan/helm-chart.git
    targetRevision: main
    path: .
    helm:
      releaseName: application-stack
      valueFiles:
        - environments/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: application-prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
